name: AppImage Build
on: push 
jobs: 

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - name: Install required dependencies
      run: sudo apt-get install desktop-file-utils zsync python qt5-default

    # Runs a set of commands using the runners shell
    - name: Build AppImage
      run: |
        wget -nv -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        ./linuxdeploy-x86_64.AppImage --appimage-extract
        
        

    - name: Release AppImage
      uses: ncipollo/release-action@v1.11.1
      with:
        name: kcc-${{ env.VERSION }}.AppImage
        allowUpdates: True
        prerelease: False
        artifacts: "${{ env.NAME }}*.AppImage*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: False
        omitBodyDuringUpdate: False
        tag: v${{ env.VERSION }}
        replacesArtifacts: true
    - name: Upload Artifacts
      if: ${{ github.ref != 'refs/heads/trunk' }}
      uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: ${{ env.NAME }}*.AppImage*
